### PR TITLE
fix: adjust eu-logo and button width in mobile view

### PR DESCRIPTION
**Pull request by YouQam**

### CODE REVIEW

**Review by umut0 — CHANGES_REQUESTED** [review]
image
This problem also happens in the backpack due to the BadgeCards, we should make a small version of this card too. (WIll also be an issue in the upcoming Learningpath changes)

**Comment by timber-they** [comment]
@umut0 why didn't you move the card? Now that was quite confusing ^^

**Comment by umut0** [comment]
> @umut0 why didn't you move the card? Now that was quite confusing ^^

sorry. forgot.

**Comment by YouQam** [comment]
> This problem also happens in the backpack due to the BadgeCards, we should make a small version of this card too. (WIll also be an issue in the upcoming Learningpath changes)

This occurred due to width of search-badge input. I've updated it.

**Review by umut0 — APPROVED** [review]

**Pull request merged**
