### PR TITLE
#61: show correct issuer staff role

### PR DESCRIPTION
**Pull request by YouQam**
This PR fixes the issue of not being able to change issuer role to something else than owner.

### CODE REVIEW

**Comment by timber-they** [comment]
The issue was referring to the admin panel (where it shouldn't be possible to change the role of the creator of an issuer to something else than owner, which got reverted automatically on the next edit), so this can't solve that problem.

**Review by timber-they — CHANGES_REQUESTED** [review]
To be honest I also don't understand how this would solve any problem at all. If it does fix *some* problem (even though it certainly doesn't fix the problem from the card), then I guess it can still be merged.

**Comment by YouQam** [comment]
> To be honest I also don't understand how this would solve any problem at all. If it does fix _some_ problem (even though it certainly doesn't fix the problem from the card), then I guess it can still be merged.

It solve the problem of adding/update an issuer member, it always remain as an `owner` although the default value is `staff`.

**Comment by timber-they** [comment]
I don't quite understand. In my understanding forcing it to be `owner` is the intended behavior

**Comment by YouQam** [comment]
> which got reverted automatically on the next edit



> I don't quite understand. In my understanding forcing it to be `owner` is the intended behavior

But the default value in DB is `staff` also if you update it it doesn't resist after page reload? Try this out with the version already deployed to see the difference.

**Comment by YouQam** [comment]
This PR doesn't refer to this card  [server: Don't allow change to role of issuers creator](https://github.com/mint-o-badges/badgr-ui/issues/61) anymore, now it refers to [ui: add/update staff member doesn't show correct staff role](https://github.com/mint-o-badges/badgr-ui/issues/71)

**Pull request closed without merging**
