### PR TITLE
Feat/add qr code vergabe to badge table

### PR DESCRIPTION
**Pull request by YouQam**

### CODE REVIEW

**Review by jona159 — CHANGES_REQUESTED** [review]
According to the figma design, on the mobile view, the "Empfänger:innen" column should still be shown and the badge name should also still be shown

**Comment by YouQam** [comment]
> According to the figma design, on the mobile view, the "Empfänger:innen" column should still be shown and the badge name should also still be shown

Now both are shown.

**Comment by jona159** [comment]
> > According to the figma design, on the mobile view, the "Empfänger:innen" column should still be shown and the badge name should also still be shown
> 
> Now both are shown.

Looks almost right, just one small thing. On mobile, if the badge name is longer and takes more than one row it is covered by the button "Badge direkt vergeben". I think we could probably use "flex-wrap" to force the badge name on one line on mobile, alternatively increase the margin between the text and button please

**Comment by YouQam** [comment]
> > > According to the figma design, on the mobile view, the "Empfänger:innen" column should still be shown and the badge name should also still be shown
> > 
> > 
> > Now both are shown.
> 
> Looks almost right, just one small thing. On mobile, if the badge name is longer and takes more than one row it is covered by the button "Badge direkt vergeben". I think we could probably use "flex-wrap" to force the badge name on one line on mobile, alternatively increase the margin between the text and button please

Thanks for your feedback. I made some updates now it looks exactly as in Figma design.

**Review by jona159 — APPROVED** [review]

**Pull request merged**
