### PR TITLE
Feat/limit badge description

### PR DESCRIPTION
**Pull request by jona159**

### CODE REVIEW

**Comment by timber-they** [comment]
Note that there's a merge conflict

**Review by timber-they — CHANGES_REQUESTED** [review]
The error message for the issuer with a too long description / name is "Bitte gebe eine Beschreibung / Namen an", which is grammatically wrong (should be "gib") and also doesn't make sense for too long content.

**Comment by jona159** [comment]
> The error message for the issuer with a too long description / name is "Bitte gebe eine Beschreibung / Namen an", which is grammatically wrong (should be "gib") and also doesn't make sense for too long content.

I fixed the grammar in all occurences now, but the error message is shown correctly when i try it. Could you check again?

**Review by timber-they — CHANGES_REQUESTED** [review]
My point wasn't that the error message isn't shown, but that the content doesn't make sense. Saying "Bitte gib ... an" is not the correct error message for too long content; it should be sth like "Bitte gib weniger als ... Zeichen ein" or similar

**Comment by jona159** [comment]
> My point wasn't that the error message isn't shown, but that the content doesn't make sense. Saying "Bitte gib ... an" is not the correct error message for too long content; it should be sth like "Bitte gib weniger als ... Zeichen ein" or similar
description_error

@timber-they  For me this error message is shown if the description is too long, can you specify on what page the incorrect message is shown?

**Pull request merged**
